export enum Menu {
  'MAIN' = 'MAIN',
  'GIT' = 'GIT',
  'GENERATOR' = 'GENERATOR',
  'SCAFFOLDER' = 'SCAFFOLDER',
  'SELECT_TEMPLATES' = 'SELECT_TEMPLATES',
  'SELECT_PACKAGE_MANAGER' = 'SELECT_PACKAGE_MANAGER',
}
